title: Content
baseurl: 'https://red-list-ecosystem.github.io/typology-map-content'
imageurl: 'https://red-list-ecosystem.github.io/typology-map-content/assets/uploads'
siteurl: 'https://red-list-ecosystem.github.io/typology-map-content/'
permalink: /:categories/:title
markdown: kramdown
languages: &languages
  - name: 'English'
    value: 'en'
prose:
  media: "assets/uploads"
  rooturl: '_posts'
  siteurl: 'https://red-list-ecosystem.github.io/typology-map-content/'
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "default"
    - name: "permalink"
      field:
        element: "text"
        label: "Permalink"
        value: "/"
    - name: "title"
      field:
        element: "text"
        label: "Title"
        value: ""
  _posts/explore:
    - name: "layout"
      field:
        element: "hidden"
        value: "explore"
    - name: "permalink"
      field:
        element: "text"
        label: "Permalink"
        value: "/"
    - name: "title"
      field:
        element: "text"
        label: "Title"
        value: ""
    - name: "content-id"
      field:
        element: "text"
        label: "ID"
        value: ""
